server:
  port: 8065
  
spring:
  application:
    name: API_GATEWAY
   
  cloud:
    gateway:
      routes:
      - id: ORDER-SERVICE
        uri:
          lb://ORDER-SERVICE
        predicates:
        - Path=/order/**
        
      - id: PAYMENT-SERVICE
        uri:
          lb://PAYMENT-SERVICE
        predicates:
        - Path=/payment/**
      
      